let str = "String";
let num = 5;
let none;
let bool = true;
let arr = [3,3,40];
console.log(typeof(str));
console.log(typeof(num));
console.log(typeof(none));
console.log(typeof(bool));
console.log(typeof(arr));